require("indent_blankline").setup {
  char = "▎",
  use_treesitter = true,
  show_current_context = true,
  show_current_context_start = true,
  show_trailing_blankline_indent = false,
  show_first_indent_level = false,
  context_patterns = {
    "class",
    "return",
    "function",
    "method",
    "^if",
    "^while",
    "jsx_element",
    "^for",
    "^object",
    "^table",
    "block",
    "arguments",
    "if_statement",
    "else_clause",
    "jsx_element",
    "jsx_self_closing_element",
    "try_statement",
    "catch_clause",
    "import_statement",
    "operation_type",
  },
  buftype_exclude = {"terminal"},
  filetype_exclude = {"help", "terminal", "text", "markdown", "git", "NvimTree"},
  colorcolumn = "99999"
}
